package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import model.User;

public class UserDaoImpl implements UserDao {
	private static final String DB_URL = "jdbc:mysql://localhost:3306/login_and_register";
	private static final String DB_USERNAME = "root";
	private static final String DB_PASSWORD = "mysqlpassword";
	private static final String SELECT_USER_QUERY = "SELECT email,password from users WHERE email=? AND password =?";

	private Connection getConnection() {
		Connection connection = null;
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			connection = DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return connection;
	}

	@Override
	public User getUser(String email, String password) {
		// TODO Auto-generated method stub
		User user = null;
		try (Connection con = getConnection();
				PreparedStatement selectStatement = con.prepareStatement(SELECT_USER_QUERY);) {

			selectStatement.setString(1, email);
			selectStatement.setString(2, password);
			ResultSet rs = selectStatement.executeQuery();
			// boolean execute(): may be any kind of SQL statement.
			// ResultSet executeQuery(): returns the ResultSet object generated by the
			// query.
			// int executeUpdate(): must be an SQL INSERT, UPDATE or DELETE statement; or an
			// SQL statement that returns nothing, such as a DDL statement.
			while (rs.next()) {
				String emailFromQuery = rs.getString("email");
				String passwordFromQuery = rs.getString("password");
				user = new User();
				user.setEmail(emailFromQuery);
				user.setPassword(passwordFromQuery);
			}

		} catch (SQLException e) {

			e.printStackTrace();
		}
		return user;
	}

	@Override
	public void addUser(User user) {
		// TODO Auto-generated method stub

	}

}
